### ISSUE TITLE
Tailwind Icon Color 

### ISSUE THREAD

**Issue by nilsvennemann** [lucaburgio/iconoir#126] opened 2022-02-14 17:50 UTC
When you use TailwindCSS you cant change the Color with `text-blue-600`. Please Fix it!

**Comment by lucaburgio** [comment] 2022-03-10 08:51
@nilsvennemann Could add more info and describe your process?

**Comment by nilsvennemann** [comment] 2022-03-10 08:52
You can't make text-red-600 as example the icon don't change the color

**Comment by sammarks** [comment] 2022-03-14 19:15
@nilsvennemann are you using the React package, or are you just using the CSS styles?

**Comment by nilsvennemann** [comment] 2022-03-27 04:51
Css Style

**Comment by paescuj** [comment] 2022-04-02 16:16
This is a duplicate of #120. Technically, it's not possible to change the color at the moment. I can take a look at this over the next week!

**Closed** 2022-04-23 22:08 UTC
Labels: duplicate, Issue
